version: '3.8'

services:
  php:
    build: .
    ports:
      - "8081:80" # Changed to 8081 to avoid conflict with Jenkins
    volumes:
      - .:/var/www/html

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000" # Changed to 9000 for consistency
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube # ✅ Removed incorrect period
