name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version

      - name: Start SonarQube Docker container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube
          sleep 60 # Increased to give SonarQube more time to initialize

      - name: Wait for SonarQube to be ready
        run: |
          echo
